### ISSUE TITLE
Proposed changes to Home.md

### ISSUE THREAD

**Issue by cgendreau** [DINA-Web/documentation#1]
@kcranston and I would like to propose some changes to the documentation wiki.
The main idea is to bring the different modules in the index to facilitate the finding of specific pieces.

Please see the proposed changes below regarding the `Home.md` file of the wiki. If we agree, I will change it directly in the wiki (and the links to other wiki pages will work).
____

Index of DINA-Web system documentation:

# Overview
- [[Overview]] of the goals, guidelines, principles and decisions.

# User manual
- [[User manual]] for collection managers.

# Modules
## Accounts management
 - [[ Account Management ]] documentation
 - GitHub [Account-Management]( https://github.com/DINA-Web/documentation/wiki/Account-Management) project

## Collection management
 - [[ Collection Management ]] documentation
 - [Use Cases](https://github.com/DINA-Web/dina-collections-data-model-use-cases)
 - GitHub [Collection-Management](https://github.com/DINA-Web/documentation/wiki/Collection-Management) project
 - GitHub [DINA-collections-data-model](https://github.com/DINA-Web/dina-collections-data-model) project

## Taxonomy management
 - [[ Taxonomy Management ]] documentation

# Developers documentation
 - [Guidelines](https://github.com/DINA-Web/guidelines)
 - [[ Development manual ]] for developers
 - [[ Technology-overview ]]
 - [[ Docker Practices ]]

# Private Space
Login required

## Tasks
* [Current tasks are tracked on Redmine](https://support.dina-web.net/projects/dina-web-collection-management-system/agile/board?utf8=%E2%9C%93&set_filter=1&f%5B%5D=tracker_id&op%5Btracker_id%5D=%3D&v%5Btracker_id%5D%5B%5D=2&f%5B%5D=status_id&op%5Bstatus_id%5D=%3D&f_status%5B%5D=12&f_status%5B%5D=2&f_status%5B%5D=7&f_status%5B%5D=3&c%5B%5D=id&c%5B%5D=project&c%5B%5D=assigned_to&c%5B%5D=relations&c%5B%5D=story_points)
 (requires login)

## Services

This contains all services related to DINA. Please see the [[User Manual]] for links only to regular user interface  (requires login). 

* Collections manager: https://alpha-cm.dina-web.net/login
   * Mockup data version: https://alpha-cm-mock.dina-web.net/login
* Style guide: https://alpha-style.dina-web.net/
* API schema and documentation: https://alpha-api-docs.dina-web.net/
* Keycloak account management console: https://alpha-keycloak.dina-web.net
* Slim-Taxonomy mockup API: https://alpha-slim-taxonomy.dina-web.net

_Parts of the manual are **work-in-progress** or still awaiting final decisions (**TBD**).
Manual will be written in English. (Possible translations of stabilized documentation will be discussed later.)_

**Comment by mikkohei13** [comment]
Thanks for the suggestions! I'd like to keep the front page quite short and simple, so that it's not overwhelming for non-technical end users. See latest changes - do you feel this is good for finding the pieces?

**Comment by kcranston** [comment]
Thanks, @mikkohei13 ! Looks better. @cgendreau and I just started at AAFC and are trying to get up to speed on DINA. You may see minor changes to the wiki from us in the future (assuming that is ok).

**Comment by mikkohei13** [comment]
Ok. Note that many things have been changing here at NRM lately (project plan & some tools, people and technologies), and the wiki doesn't yet reflect all the changes. I'll be doing some more changes soon. Ask me or Stefan if you want to know something specific.
