### ISSUE TITLE
How many DINA systems / modules per institution?

### ISSUE THREAD

**Issue by kcranston** [DINA-Web/documentation#3]
I have some high-level questions about the DINA system (triggered by discussion of the [taxonomy](https://github.com/DINA-Web/taxonomy) module, but pertain to development as a whole). I assume that:

* DINA consists of multiple modules (collection, taxonomy, etc)
* An institution (e.g. Naturhistoriska riksmuseet, Agriculture and Agri-Food Canada) can have multiple collections (e.g. mammals, fungi, plants)

Will a single institution install:

1. A single DINA system with one instance of each module
1. A single DINA system with one or more instance of each module (e.g. one taxonomy module and multiple collection modules, or one collection module with multiple taxonomy modules)
1. Multiple DINA systems (one for each collection)

Will there be a single user interface for each _institution_ or each _DINA installation_ or each _collection_?

**Comment by antonoberg** [comment]
We dont know the answers to all these questions but here is an attempt: 

DINA consists of multiple modules (collection, taxonomy, etc): 
**yes**

An institution (e.g. Naturhistoriska riksmuseet, Agriculture and Agri-Food Canada) can have multiple collections (e.g. mammals, fungi, plants): 
**yes**

Will a single institution install:
1. A single DINA system with one instance of each module
**Likely not**

2. A single DINA system with one or more instance of each module (e.g. one taxonomy module and multiple collection modules, or one collection module with multiple taxonomy modules)
**maybe**

3. Multiple DINA systems (one for each collection)
**maybe**

Will there be a single user interface for each institution or each DINA installation or each collection?
**Dont know**

In the way that we are building the collection management system decisions related to how the different modules will be run can be made later. From speaking to Karin I got the impression that these questions needs to be answered soon for the taxonomy module. I guess its good to start these discussions when we meet in Berlin.

**Comment by gnewton** [comment]
On 21 February 2018 at 11:24, antonoberg <notifications@github.com> wrote:

> We dont know the answers to all these questions but here is an attempt:
>
> DINA consists of multiple modules (collection, taxonomy, etc):
> *yes*
>
Yes.

> An institution (e.g. Naturhistoriska riksmuseet, Agriculture and Agri-Food
> Canada) can have multiple collections (e.g. mammals, fungi, plants):
> *yes*
>
Yes

> Will a single institution install:
>
>    1.
>
>    A single DINA system with one instance of each module
>    *Likely not*
>
> >A single DINA system with one instance of each module
Yes. That was the original architecture. If Sweden is changing this, then
we need to talk.
But are we talking about the same thing? The original architecture was/is: *a
single DINA instance has one instance of each module; different DINA
instances might use different implementations of modules.*


>    1.
>    2.
>
>    A single DINA system with one or more instance of each module (e.g.
>    one taxonomy module and multiple collection modules, or one collection
>    module with multiple taxonomy modules)
>    *maybe*
>    3.
>
>    Multiple DINA systems (one for each collection)
>    *maybe*
>
> Will there be a single user interface for each institution or each DINA
> installation or each collection?
> *Dont know*
>
Not sure what this question is referring to. GUIs will be skinnable as per
their local install.
Note: in case it is not been made explicit: different DINA instances have
nothing to do with one another and do not know about one another (i.e. the
AAFC instance would have no knowledge of  the Stockholm one...)

> In the way that we are building the collection management system decisions
> related to how the different modules will be run can be made later.
>
Not sure what this means. All APIs are defined up front. All implementing
modules need to adhere to the APIs. APIs are what holds this project
together.


> From speaking to Karin I got the impression that these questions needs to
> be answered soon for the taxonomy module. I guess its good to start these
> discussions when we meet in Berlin.
>
These questions need to be settled on for all modules. We thought they were.

Glen

**Comment by kcranston** [comment]
Based on the discussion here and at the Berlin meeting, it seems that this is the model:

1. An institution will install a single DINA system
1. A DINA system includes one copy of each module, noting that an institution may choose among different implementations for a given module
1. A DINA system can hold data for more than one collection

Can I get a +1 to indicate agreement? @mikkohei13 ?

**Comment by gnewton** [comment]
+1

**Comment by mikkohei13** [comment]
+1, but. I have been thinking this as the default, but it should not be set in stone, in case good reasons for doing otherwise come up.

**Comment by kcranston** [comment]
Closing this, as we seem to have general agreement. @mikkohei13 -when making downstream design decisions about the various modules, we can try and note cases where a decision would make a future deviation from the default difficult.

**Comment by gnewton** [comment]
It is a major architectural question where there is only one module per
service, or multiple modules per service running. The latter implies
greater complexity as it involves introducing discoverability, and things
like 'so which service do I (a client application) use"?
Has a compelling use case for this been expressed?

Glen
